version: 0.0
os: linux
files:
  - source:  /
    destination: /opt/Application

permissions:
  - object: /opt/Application
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root