version: '2'
services:
  app:
    build: .
    ports:
      - "5000:8080"
    links:
      - redis
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]