server:
  #포트
  port: 8080
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
  #DB 설정
  datasource:
    url: jdbc:h2:mem:the_moment
    driver-class-name: org.h2.Driver
    username: sa
  #JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  #profile
  profiles:
    active: dev