server:
  #포트
  port: 8080
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.moment.the.config.mvc.RequestResponseLoggingFilter: debug
    org.hibernate.SQL: debug
  #    org.hibernate.type: trace
  charset:
    console: UTF-8
  file:
    name: ./logs/product.log
    path: ./logs/product.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-file-size: 500MB
      max-history: 1

spring:

  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # Mysql RDB 설정
  datasource:
    url: jdbc:mysql://the-moment-database.ctiaukyhm1vp.us-east-2.rds.amazonaws.com:3306/TheMoment
    username: admin
    password: themoment
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: create
    show-sql: true
    generate-ddl: true
    database: mysql

  #Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

  # Redis
  redis:
    image: redis:latest
    host: redis
    port: 6379

  jwt:
    secret: asdkfhksldjhfkajsdhfasd7df67sa8d6f87as6df86sa8d7f6a8ds6f87a9s6d8f76sad87f687ad6f8asd76f8asd6f8asd6f87sd6f87asd6f87s