server:
  #포트
  port: 8080
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # Mysql RDB 설정
  datasource:
    url: jdbc:mysql://tm-database.cnhuvlmnjbfa.ap-northeast-2.rds.amazonaws.com:3306/TheMoment
    username: admin
    password: themoment
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql

  #Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: asdkfhkslasdfasdfasd#$@%8d7f6a8ds6f87a@#$%9s6d8f76sad87f687ad6f8asd76f8a@#$asdf